quotes/quoteapp/urls.py
from django.urls import path
from . import views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('author/', views.author, name='author'),
    path('quote/', views.quote, name='quote'),
    path('tag/', views.tag, name='tag'),
    path('detail/<int:quote_id>', views.detail, name='detail'),
    path('find_author/<int:author_id>', views.find_author, name='find_author'),
]

quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
]

quotes/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

quotes/quoteapp/models.py
from django.db import models


class Author(models.Model):
    full_name = models.CharField(max_length=100, null=False)
    born_date = models.CharField(max_length=100, null=False)
    born_location = models.CharField(max_length=150, null=False)
    bio = models.CharField(max_length=4000, null=False)

    def __str__(self):
        return f"{self.full_name}"


class Tag(models.Model):
    name = models.CharField(max_length=25, null=False)

    def __str__(self):
        return f'{self.name}'


class Quote(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    quote = models.CharField(max_length=2000, null=False)
    tags = models.ManyToManyField(Tag)
    
    def __str__(self):
        return f"{self.author.full_name}: {self.quote}, {self.tags}"

    def quotes_author(self):
        return self.author
    

quotes/users/models.py
from django.db import models

# Create your models here.

quotes/quoteapp/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField
from .models import Author, Quote, Tag


class AuthorForm(ModelForm):
    full_name = CharField(max_length=100, required=True, widget=TextInput)
    born_date = CharField(max_length=100, required=True, widget=TextInput)
    born_location = CharField(max_length=150, required=True, widget=TextInput)
    bio = CharField(max_length=4000,required=True, widget=TextInput)

    class Meta:
        model = Author
        fields = ['full_name', 'born_date', 'born_location', 'bio']


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']


class QuoteForm(ModelForm):
    author = ModelChoiceField(queryset=Author.objects.all())
    quote = CharField(max_length=2000, required=True, widget=TextInput)

    class Meta:
        model = Quote
        fields = ['author', 'quote']
        exclude = ['tags']

quotes/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

quotes/quoteapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import QuoteForm, AuthorForm, TagForm
from .models import Author, Quote, Tag


def main(request):
    quotes = Quote.objects.all()
    return render(request, 'quoteapp/index.html', {"quotes": quotes})


def quote(request):
    authors = Author.objects.all()
    tags = Tag.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()

            choice_authors = Author.objects.filter(full_name__in=request.POST.getlist('authors'))
            for author in choice_authors.iterator():
                new_quote.authors.add(author)
            
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/quote.html', {"authors": authors, "tags": tags, 'form': form})

    return render(request, 'quoteapp/quote.html', {"authors": authors, "tags": tags, 'form': QuoteForm()})


def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/author.html', {'form': form})

    return render(request, 'quoteapp/author.html', {'form': AuthorForm()})


def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/tag.html', {'form': form})

    return render(request, 'quoteapp/tag.html', {'form': TagForm()})


def detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    author = Author.objects.get(id=quote.author_id)
    
    return render(request, 'quoteapp/detail.html', {"quote": quote, "author": author})


def find_author(request, author_id):
    author = Author.objects.get(id=author_id)
    
    return render(request, 'quoteapp/find_author.html', {"author": author})

quotes/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages 
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .forms import LoginForm, RegisterForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quoteapp:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect('main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quoteapp:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quoteapp:main')

quotes/quoteapp/templates/quoteapp/author.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter author's name:
            {{form.full_name}}
        </label>
        <span>{{ form.errors.full_name }}</span>
        <label>Enter author's born date:
            {{form.born_date}}
        </label>
        <span>{{ form.errors.born_date }}</span>
        <label>Enter author's born location:
            {{form.born_location}}
        </label>
        <span>{{ form.errors.born_location }}</span>
        <label>Enter author's biography:
            {{form.bio}}
        </label>
        <span>{{ form.errors.bio }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quote information</title>
    <nav>
        <ul>
            <li style="padding: 40px" class="scape"><a href="/" role="banner"> Quotes to Scrape </a></li>
        </ul>
    </nav>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}">
</head>
<body>
<main style="margin-top: -60px" class="container">
    {% block content %} {% endblock %}
</main>
</body>
</html>

quotes/quoteapp/templates/quoteapp/detail.html
{% extends "quoteapp/base.html" %}

{% block content %}
{% load extract_tags %}

<div class="container-fluid">
    <p class="text">{{ quote.quote }}</p>
    <p>by <small class="author">{{ author.full_name }}</small></p>
    <p>Tags: <small> {{ quote.tags|tags }} </small></p>
</div>

{% endblock %}

quotes/quoteapp/templates/quoteapp/find_author.html
{% extends "quoteapp/base.html" %}

{% block content %}

<div class="container-fluid">
    <p>
        <strong>{{ author.full_name }}</strong>
    </p>
    <p>
        Born date: {{ author.born_date }}
    </p>
    <p>
        Born in: {{ author.born_location }}
    </p>
    <p>
        Biography: {{ author.bio }}
    </p>
</div>

{% endblock %}

quotes/quoteapp/templates/quoteapp/find_quote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quote information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}">
    {% load extract_tags %}
</head>
<body>
<main style="margin-top: 40px" class="container">
    <div class="container-fluid">
        <p class="text">{{ quote.quote }}</p>
        <p>by <small class="author">{{ quote.quotes_author }}</small><a href="find_author/{{ quote.author_id }}"> (about)</a></p>
        <p>Tags: <small> {{ quote.tags|tags }} </small></p>
    </div>
</main>
</body>
</html>

quotes/quoteapp/templates/quoteapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes to Scrape</title>
    <nav>
        <ul>
            <li style="padding: 40px" class="scape"><a href="/" role="banner"> Quotes to Scrape </a></li>
        </ul>
    </nav>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}">
</head>
<body>
<main style="margin-top: -60px" class="container">
    <nav>
        {% if user.is_authenticated %}
            <ul>
                <li><a href="{% url 'quoteapp:author' %}" role="button">Add author</a></li>
                <li><a href="{% url 'quoteapp:quote' %}" role="button">Add quote</a></li>
                <li><a href="{% url 'quoteapp:tag' %}" role="button">Add Tag</a></li>
            </ul>
            <ul>
                <li>Welcome <b>{{ user.username }}!</b></li>
                <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
            </ul>
            {% else %}
            <ul>
                <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
            </ul>
            {% endif %}
    </nav>
    <div class="main-container">
        <div class="item item_1">
        {% for quote in quotes %}
            <div>
                {% if quote %}
                    <p>
                        {% include "quoteapp/find_quote.html" with id=quote.author_id%}
                    </p>    
                {% else %}
                    No quotes(
                {% endif %}
            </div> 
        {% endfor %}
        </div>
        <div class="item item_2">
            Top 10 tags:
        </div>
    </div>
    
    

</main>
</body>
</html>

quotes/quoteapp/templates/quoteapp/quote.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Select author:
            <select name="author">
                {% for author in authors %}
                <option value="{{author.id}}">{{ author.full_name }}</option>
                {% endfor %}
            </select>
        </label>
        <label>Enter the quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quoteapp/templates/quoteapp/tag.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/users/templates/users/login.html
{% extends "quoteapp/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/users/templates/users/signup.html
{% extends "quoteapp/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}